resources:
- deployment.yaml
<<<<<<< Updated upstream

# helmCharts:
# - name: tenant
#   repo: https://operator.min.io/
#   version: 5.0.6
#   releaseName: tenanat
#   namespace: capture
=======
- minio-dev.yaml
>>>>>>> Stashed changes
