apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: capture
  labels:
    app: capture
spec:
  serviceName: capture
  selector:
    matchLabels:
      app: capture
  replicas: 0
  template:
    metadata:
      labels:
        app: capture
    spec:
      volumes:
      - name: video0
        hostPath:
          path: /dev/video0 
          # type: CharDevice
      containers:
      - name: capture
        image: us-west1-docker.pkg.dev/davec-anthos-next/docker/capture:1.7
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /dev/video0
            name: video0
        env:
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio
              key: accesskey
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio
              key: secretkey
        - name: MINIO_HOST
          value: "capture:5000"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - doit-4
---
apiVersion: v1
kind: Service
metadata:
  name: capture
  namespace: capture
spec:
  selector:
    app: capture
  type: ClusterIP
  ports:
  - name: capture
    protocol: TCP
    port: 80
    targetPort: 5000
