kind: ConfigMap
apiVersion: v1
metadata:
  namespace: capture
  name: computer-vision-sa-config
data:
  config: |
    {
      "type": "external_account",
      "audience": "identitynamespace:davec-anthos-next.svc.id.goog:https://gkehub.googleapis.com/projects/davec-anthos-next/locations/global/memberships/doit-edge-next",
      "service_account_impersonation_url": "https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/computer-vision-sa@davec-anthos-next.iam.gserviceaccount.com:generateAccessToken",
      "subject_token_type": "urn:ietf:params:oauth:token-type:jwt",
      "token_url": "https://sts.googleapis.com/v1/token",
      "credential_source": {
        "file": "/var/run/secrets/tokens/gcp-ksa/token"
      }
    }
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: computer-vision-sa
  namespace: capture   
automountServiceAccountToken: false
---